version: 1.0.{build}

skip_tags: false

image: Visual Studio 2015

environment:
  VCVARSALL: '"C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\vcvarsall"'
  matrix:
  - DC: dmd
    ARCH: x86
  - DC: dmd
    ARCH: x86_64
#  - DC: ldc2
#    ARCH: x86
#  - DC: ldc2
#    ARCH: x86_64
#  - DC: gdc
#    ARCH: x86
#  - DC: gdc3
#    ARCH: x86_64
install:
  - ps: function SetUpDCompiler {
        if($env:DC -eq "dmd") {
          echo "*** Getting latest dmd version... ***";
          $TempDir = [System.IO.Path]::GetTempPath();
          $env:DCVER = Invoke-WebRequest -URI "http://downloads.dlang.org/releases/LATEST";
          echo "*** $($env:DCVER) it is. Downloading... ***";
          Invoke-WebRequest "http://downloads.dlang.org/releases/2.x/$($env:DCVER)/dmd.$($env:DCVER).windows.7z"
            -OutFile "$($TempDir)dmd-latest.7z";
          echo "*** Unpacking... ***";
          7z x "$($TempDir)dmd-latest.7z" -o"C:\\" > $null;
          echo "*** Done! Adding it to PATH ***";
          $env:PATH += ";C:\dmd2\windows\bin;";

          echo "*** Checking dmd ***";
          dmd --version;
          echo "*** Checking dub ***";
          dub --version;
        }
      }
  - ps: SetUpDCompiler
  - ps: if($env:ARCH -eq "x86") {
        $env:VCVARS = "x86";
      } else {
        $env:VCVARS = "amd64";
      }
  - '%VCVARSALL% %VCVARS%'

build_script:
  - ps: echo "Here we go!";

test_script:
  - ps: dub build -b debug --compiler=$env:DC --arch=$env:ARCH;
  - ps: if($env:DC -ne "gdc") {
          $ErrorActionPreference = "SilentlyContinue";
          dub build -b unittest -c unittest --compiler=$env:DC --arch=$env:ARCH;
          $ErrorActionPreference = "Continue";
          .\.dub\unittest.exe -t -s -d;
        }
