sudo: false
language: d
d:
  - dmd
  - gdc
  - ldc

os:
  - linux
  - osx

env:
  - ARCH=x86_64

matrix:
  exclude:
    - d: gdc
      os: osx

script:
  - if [ "$DC" != gdc ]; then dub test --compiler=$DC --arch=$ARCH -- -t -s -d; fi
  - dub build -b debug --compiler=$DC --arch=$ARCH

before_deploy:
  - dub build -b release --compiler=$DC --arch=$ARCH
  - tar -zcf "covered-$TRAVIS_TAG-$TRAVIS_OS_NAME-$DC-x86_64.tar.gz" covered
  - export FILE_TO_UPLOAD=$(ls covered-*.tar.gz)

deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: DpB7dW6ED1sPMkhqtHZQC0pQI9aRNToKTZYIUEEJsnltbGo2F9lLjDAy0rAmMQpkGC7RXYMd1NMNFwXEjc1ORKOZKwBGKI6x28xWN85PA0M1UcFEUiqgOtMstyQwqFQTV6C+JVV8kMlatmyB+VNS4ytIn0BSYCMvtQjymZz4tmLSZiWWpj8gX119ekr97DeTWYpVdNTER7lxcXyapkOq+1OMQFXEeeJEC3tRPj1WtCfLIwSYS+jgPFeHkzU5XjCU1xO84dQlZt0o2gqCCCOId7RNtbWFBawZPK74Xs6pPVw7Yi3eiPiL8ubXobaN0zJEGYVxi0YebHQ6MkFA/bhbCjeasHngsjjyK1bxmBiZOyh+qE8w9ajQjGEVjfsJb9w0lTm6CfULdqg6jDegDZ58cSng1YI7rs1GJQLwMQmKuvl2k/3AlOeWCTudeIhrMS/GTCu9XRu4EcCQv7WLePszwD8O0G33GyoX4Gl3FSLRyddyHsx+aFX1bMdfvvH7XwovrN8uCR+vxAfBPddMc4ZJlVLoCR4Q5IlQ/kclkijRJrk6c1B19tjgUN6Qk7a8GNPG/vr/AJEWzgJ+XAlMjHH4yFyD5I7lIeslteXjHdFc7UEOpSqq2FrO5aA1RFs9nDU3LksZ5K+Nxl4GQ3MCyT4IIXkWmcCvdfwib+dYZVXUI8A=
  file_glob: true
  file: "${FILE_TO_UPLOAD}"
  on:
    repo: ohdatboi/covered
    tags: true
    condition: "$DC = ldc2"
